--- # This is a playbook to create a direcotry.
- name: my test playbook
  hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: Creating a directory
      file:
        path: /home/ansible/dhanadir
        state: directory
...

