--- # This is tow_tssks playbook
- hosts: all
  become: yes
  connection: ssh
  user: ansible

  tasks:
    - name: installing httpd software
      yum:
        name: httpd
        state: installed

    - name: start the service
      service:
        name: httpd
        state: started
...
